[build]
  publish = "dist/search-movies/browser"
  command = "npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "22"

# Production context (main branch)
[context.production]
  command = "npm run build"

# Deploy previews (pull requests)
[context.deploy-preview]
  command = "npm run build"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"

[[plugins]]
  package = "@netlify/angular-runtime"

# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true 