[build]
  publish = "dist/search-movies/browser"
  command = "npm run build:netlify-e2e"

# Environment variables
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--no-optional"
  CYPRESS_CACHE_FOLDER = "/opt/buildhome/.cache/Cypress"

# Production context (main branch)
[context.production]
  command = "npm run build:netlify-e2e"

# Deploy previews (pull requests)  
[context.deploy-preview]
  command = "npm run build:netlify-e2e"

# Branch deploys (faster builds without E2E)
[context.branch-deploy]
  command = "npm run build:netlify"

[[plugins]]
  package = "@netlify/angular-runtime"

# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true 